namespace Foundation.SitecoreCDP.Enums
{
    public enum EventType
    {
        ADD,
        ADD_CONSUMERS,
        ADD_CONTACTS,
        ADD_PRODUCT,
        CALCULATOR,
        CAMPAIGN_TRACKING,
        CLICK,
        CHAT,
        COMMENT,
        CONFIRM,
        CONTACT_REQUEST,
        CONSUMERS,
        EMAIL,
        IDENTITY,
        LOGIN,
        NOTIFICATION,
        ORDER_UPDATE,
        PAYMENT,
        PURCHASE,
        PNR_RECORD,
        SMS,
        SUBSCRIPTION,
        SEARCH,
        SELECT,
        TRIGGER,
        TRIP_SUMMARY,
        UPDATE,
        VIEW
    }
}